-- Create main links table
CREATE TABLE IF NOT EXISTS public.links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shortCode" TEXT UNIQUE NOT NULL,
  "originalUrl" TEXT NOT NULL,
  title TEXT DEFAULT 'Untitled',
  "baselineHash" TEXT NOT NULL,
  "contentLength" BIGINT DEFAULT 0,
  "createdAt" TEXT NOT NULL,
  "clickCount" BIGINT DEFAULT 0,
  "modificationCount" BIGINT DEFAULT 0,
  "lastModifiedAt" TEXT DEFAULT NULL,
  "lastCheckedAt" TEXT DEFAULT NULL
);

-- Create modifications history table
CREATE TABLE IF NOT EXISTS public.modifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shortCode" TEXT NOT NULL REFERENCES public.links("shortCode") ON DELETE CASCADE,
  "detectedAt" TEXT NOT NULL,
  "previousHash" TEXT NOT NULL,
  "newHash" TEXT NOT NULL
);

-- Create click log for analytics
CREATE TABLE IF NOT EXISTS public.clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shortCode" TEXT NOT NULL REFERENCES public.links("shortCode") ON DELETE CASCADE,
  "clickedAt" TEXT NOT NULL,
  "integrityStatus" TEXT NOT NULL
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_links_shortCode ON public.links("shortCode");
CREATE INDEX IF NOT EXISTS idx_modifications_shortCode ON public.modifications("shortCode");
CREATE INDEX IF NOT EXISTS idx_clicks_shortCode ON public.clicks("shortCode");
